### ISSUE TITLE
Allow bypass violations

### ISSUE THREAD

**Issue by fabiodomingues** [fabiodomingues/clj-depend#1]
## What?
Allow bypass some violations.

## Why?
When configuring the plugin in a legacy project that already has violations that cannot be resolved immediately. It's nice to have a way to set a baseline or allow certain violations and keep the project safe from new violations.

**Comment by ericdallo** [comment]
Maybe you can do something similar to how clj-kondo does:
```clojure
#_:clj-kondo/ignore
foo
;; or more specific for a linter
#_{:clj-kondo/ignore [:unresolved-symbol]}
bar
```

**Comment by fabiodomingues** [comment]
In addition to this suggestion above given by @ericdallo, I thought of this form within the config file itself using the `:excludes` field.

```diff
{:source-paths #{"src"}
 :layers       {:server     {:namespaces         #{sample.server}
                             :accessed-by-layers #{}}
                :controller {:defined-by         ".*\\.controller\\..*"
                             :accessed-by-layers #{:server}}
                :logic      {:defined-by         ".*\\.logic\\..*"
-                            :accessed-by-layers #{:controller}}}}
+                            :accessed-by-layers #{:controller}}}
+:excludes     [{:defined-by "foo\\.bdc.*"
+                :doc "The BDC project structure does not follow the diplomat architecture"}
+               {:namespace foo.logic.bar
+                :violation foo.controller.bar
+                :doc "The bar controller is ...."}
+               {:namespace #{foo.controller.zzz foo.logic.zzz}
+                :doc "The zzz flow does not follow the diplomat architecture"}]}
```

The idea is to place a `:doc` field (optional) to allow documenting the rationale for the decision to bypass a violation.

**Comment by fabiodomingues** [comment]
@dundalek, I would like to hear your opinion on this topic. 😊

**Comment by dundalek** [comment]
@fabiodomingues 

I would not recommend having "ignore" annotations as that could encourage bad patterns to build up over time. I consider those for cases when linter gets confused. With architecture either the code is wrong and needs to be refactored, or the layer config is wrong and needs to be relaxed.

Regarding a config option: On our project I am starting with roughly 100 existing violations, not something I would like to write in config by hand :)

The way I am thinking about enabling the workflow on CI is following. There could be two commands:
- `scripts/depend-update-violations` - runs the checker and dumps results into a snapshot file
- `scripts/depend-check` - runs the checker and print a diff from the snapshot file

Then on the CI the `scripts/depend-check` with outcomes:
- matching violations - success
- less violations - fail, but with a message in spirit of "yay, you improved the code, please run `scripts/depend-update-violations` and commit the changes"
- more violations - fail with a polite message in spirit of "please fix your code". It would be still possible to re-run the update snapshot script to accept new violations, but they would have to go out of their way to find it in docs, the message would not mention it to help them.
