### ISSUE TITLE
Ability to reverse definition of dependencies

### ISSUE THREAD

**Issue by dundalek** [fabiodomingues/clj-depend#26]
I find myself in a project with some architectural issues and it looks like clj-depend could be also useful to help enforce module boundaries (it might be slightly different use case than architecture patterns shown in the readme, but still seems applicable).

For module boundaries it would be useful to define the dependency in other order than `:accessed-by-layers` on the lower layers. Perhaps having a complementary `:accesses-layers` on the upper layers.

For example to enforce that applications can only depend on libraries (an app depending on another app would lead to violation, indicating that shared code needs to be extracted into a separate lib).
```clj
{:app-a {:defined-by         "company\\.app-a\\..*"
         :accessed-by-layers #{}}

 :lib-x {:defined-by         "company\\.lib-x\\..*"
         :accessed-by-layers #{:app-a}}
 :lib-y {:defined-by         "company\\.lib-y\\..*"
         :accessed-by-layers #{:app-a}}
 :lib-z {:defined-by         "company\\.lib-z\\..*"
         :accessed-by-layers #{:lib-x}}}
```

Now adding a new `app-b` would result in changes like that:
```diff
@@ -1,9 +1,11 @@
 {:app-a {:defined-by         "company\\.app-a\\..*"
          :accessed-by-layers #{}}
+ :app-b {:defined-by         "company\\.app-b\\..*"
+         :accessed-by-layers #{}}
 
  :lib-x {:defined-by         "company\\.lib-x\\..*"
-         :accessed-by-layers #{:app-a}}
+         :accessed-by-layers #{:app-a :app-b}}
  :lib-y {:defined-by         "company\\.lib-y\\..*"
          :accessed-by-layers #{:app-a}}
  :lib-z {:defined-by         "company\\.lib-z\\..*"
-         :accessed-by-layers #{:lib-x}}}
+         :accessed-by-layers #{:app-b :lib-x}}}

```

Compared to if we defined dependencies in reversed order:
```clj
{:app-a {:defined-by      "company\\.app-a\\..*"
         :accesses-layers #{:lib-x :lib-y}}

 :lib-x {:defined-by      "company\\.lib-x\\..*"
         :accesess-layers #{:lib-z}}
 :lib-y {:defined-by      "company\\.lib-y\\..*"}
 :lib-z {:defined-by      "company\\.lib-z\\..*"}}
```

Same addition would be more localized and would look like:
```diff
@@ -1,5 +1,7 @@
 {:app-a {:defined-by      "company\\.app-a\\..*"
          :accesses-layers #{:lib-x :lib-y}}
+ :app-b {:defined-by      "company\\.app-b\\..*"
+         :accesses-layers #{:lib-x :lib-z}}
 
  :lib-x {:defined-by      "company\\.lib-x\\..*"
          :accesess-layers #{:lib-z}}
```

**Comment by fabiodomingues** [comment]
Hi @dundalek! Amazing suggestion. Could you please review this [PR](https://github.com/fabiodomingues/clj-depend/pull/30)?

**Comment by fabiodomingues** [comment]
@dundalek I'm wondering if the correct thing should be `access-layers` instead of `accessed-layers`. What do you say?

**Comment by dundalek** [comment]
To me it seems the opposite: `access-layers` is a plural form and could by used instead of `accesses-layers`, but `accessed-by-layers` is the opposite.

(The doubling of `c`s and `s`s is in the word is unfortunate (prone to typos), but that's just English. An alternative I can think of could be for example *use* - `uses`, `used-by`)


For example if A depends on X and B depends on X then:

singular:
- A access**es** X
- B access**es** X
- X is access**ed** by A (inverse direction of the relationship)

plural:
- A and B access X (`access` without suffix)

```mermaid
flowchart LR
    A --> X
    B --> X
```

Current configuration format configures single layer at a time, therefore singular form is correct. If we wanted to use `access` in a plural form for multiple layers we would probably need to make definition and relationship definition to be separate, for example:

```edn
{:layers {:a {:defined-by "..."}
          :b {:defined-by "..."}
          :x {:defined-by "..."}}
 :relationships {#{:a :b} {:access-layers #{:x}}}}
```
