### ISSUE TITLE
Print violated layers

### ISSUE THREAD

**Issue by dundalek** [fabiodomingues/clj-depend#27]
It would be useful to print which which layer relationship is being violed, sometimes it is tricky to determine just by the namespaces. Especially when a namespace is part of multiple patterns/layers.

**Comment by fabiodomingues** [comment]
Nowadays the violation structure looks like this:

```clojure
{:namespace 'foo.c.bar
 :dependency-namespace 'foo.b.bar
 :message "\"foo.c.bar\" should not depend on \"foo.b.bar\""}
```

When placing the layer information it would look like this:

```clojure
{:namespace 'foo.c.bar
 :layer :c
 :dependency-namespace 'foo.b.bar
 :dependency-layer :b
 :message "\"foo.c.bar\" of layer \":c\" should not depend on \"foo.b.bar\" of layer \":b\""}
```

@dundalek did you think of any different way? Share your idea, it is welcome.

**Comment by dundalek** [comment]
@fabiodomingues That looks great!

I am thinking the message could alternatively be something like `"foo.c.bar" should not depend on "foo.b.bar" (layer ":c" on ":b")`. As an information hierarchy the namespaces are printed first, so when it is obvious one can already act on it when checking which seems the most common use case. The layers are useful for less common cases when it is not obvious, or when working/debugging the layer config.
